### ISSUE TITLE
Logging configuration

### ISSUE THREAD

**Issue by Bios-Marcel** [TradeWars/Economy#3]
We need to decide on some logging specific settings:

* How often do we create new logfiles?
* How big can a logfile get
* How much previous logfiles do we want to keep?
* Name of the logfiles
* Location of logfiles
* Format

Those are our settings for now:

https://github.com/TradeWars/Economy/commit/2b5450764142308742d842a08e9f6d6ff80c2d20#diff-4f5265034ad4532f84f377920f9df03e

Note that this is just a first proposal and can be changed any time.

**Comment by Southclaws** [comment]
Log files are quite archaic nowadays - since we're deploying to a Docker stack, the production configuration must log to standard out only, no log files because the container filesystem is ephemeral and non-persistent.

Output from all containers is collected by a logging aggregator such as Logstash or Logspout and directed to a database such as Elasticsearch or a more traditional log store like syslog.

Log lines should be self contained JSON objects, not raw text - raw text is usually either unstructured, custom made for the app or language specific. JSON is a standard encoding and can contain arbitrary fields relevant to the event being recorded.

The useful thing about this is Kibana (or whatever frontend I choose to use) can be used to search logs. The additional benefit of using JSON is you don't need to create complex, brittle and annoying regular expressions to match things like exceptions or errors. You just read the `level` field or whatever, check if it's `warn`/`error`/whatever and then fire off an Email or Discord message.

Resources:

- https://www.loggly.com/blog/why-json-is-the-best-application-log-format-and-how-to-switch/
- https://juxt.pro/blog/posts/logging.html
- https://logz.io/learn/complete-guide-elk-stack/

**Comment by Bios-Marcel** [comment]
Uhm what .... loglines should be json?

I think logoutput should be readable or do you think it doesn't matter since we won't ever see the commandline anyways?

**Comment by Southclaws** [comment]
Yes, it may sound weird if you've always used text based logs but it's true, humans rarely read log files now and they shouldn't need to.

The whole idea of JSON is that computers can read it. It's simple for a computer to read the `type` field and check if it's `error` or whatever, but it's significantly harder and more performance intensive to scan log text for words like `error` or `fatal` or whatever words the programmer chose to use.

And it all goes to a database (hosted on a different machine in a "real" environment - unfortunately I probably won't do that) that you can search and query from a web frontend (no more sharing SSH access!)

**Comment by Bios-Marcel** [comment]
Okay, the first implementation is ready.

## Output examples
Currently it's output looks like this if there is no stacktrace:
```JSON
{"message":"Registration of UncaughtExceptionHandler successful.","time":"2018-07-22 23:12:08.202","threadName":"main","className":"org.tradewars.economy.MainKt","methodName":"initializeUnhandledExceptionHandler","lineNumber":23,"logLevel":"info"}
```

and like this if there is a stracktrace:
```JSON
{"message":"Uncaught Exception in thread main: ","stackTrace":"java.lang.IllegalStateException\n\tat org.tradewars.economy.MainKt.main(Main.kt:13)\n","time":"2018-07-22 23:42:02.049","threadName":"main","className":"org.tradewars.economy.basic.UncaughtExceptionHandler","methodName":"uncaughtException","lineNumber":16,"logLevel":"error"}
```

## Which data will be printed
The implementation is quite simple, it's just using the jackson library to convert this class to JSON:
```Kotlin
@JsonInclude(JsonInclude.Include.NON_NULL)
class LogMessage(val message: String,
                 val stackTrace: String?,
                 val time: String,
                 val threadName: String,
                 val className: String,
                 val methodName: String,
                 val lineNumber: Int,
                 val logLevel: String)
```

## Dates
Dates will be formatted using: `yyyy-MM-dd HH:mm:ss.SSS`.

## Null values
For now, null values are omitted.

## Log levels
Log levels are simple string, for now there are:
* info
* warning
* error

We should discuss if need more, less or different ones.

## Usage
For now there are three message:
* info
* warning
* error

All of those take a `message: String` and a `throwable: Throwable?`. The `throwable` is usually an `Exception` and can be omitted unless wanted, it's default value is `null`.

**Comment by Southclaws** [comment]
Looks good!

**Comment by Bios-Marcel** [comment]
I will close the issue for now, if we change our mind, reopen it.
